Skip exit in wp_die() function
Automattic/wordbless pull request #30
Opened 2020-10-17 04:11 UTC by wppunk

Fixes: #28 

I've skipped `die` in the `wp_die` function.

2020-10-17 07:45 UTC, szepeviktor commented on src/WpDie.php
> +		return array( $this, $function );
@wppunk You could replace all other `array()` -s :)

2020-10-17 07:58 UTC, wppunk commented on src/WpDie.php
> +		return array( $this, $function );
@szepeviktor What do you mean? Other arrays have a long syntax

2020-10-17 08:22 UTC, szepeviktor commented on src/WpDie.php
> +		return array( $this, $function );
e.g. `$args = array()`

2020-10-17 08:28 UTC, szepeviktor requested changes

2020-10-17 08:28 UTC, szepeviktor commented on src/WpDie.php
> +		add_filter( 'wp_die_xml_handler', [ $this, 'change_handler' ], 10, 1 );
@wppunk Would you `foreach( array_keys( $this->core_handlers ) ) ... ` ?

2020-10-17 08:29 UTC, szepeviktor commented
> Short array syntax is not allowed

This is so hard!

2020-10-23 18:20 UTC, leogermani commented
Thanks for the PR!

A question worth asking. Do we want these filters enabled by default in all cases? Are there any situations when we would not want to activate this?

2020-10-23 18:23 UTC, szepeviktor commented
> Do we want these filters enabled by default in all cases?

Yes, it is reasonable to make it options. Although I do not know how.

2020-10-23 19:59 UTC, wppunk commented
@leogermani I think these filters are important by default because use the `die` function in the test stops it. This PR only starts for this and I sure next you can add other cases when need to prevent the `die` function.

2020-10-26 19:45 UTC, leogermani approved these changes
Let's merge it for now.

I think we can think of a way to disable this and other modules if we want, maybe `Wordbless\load()` could get a parameter to define that

2020-10-26 19:45 UTC, merged

2020-10-26 19:47 UTC, szepeviktor commented
That seem reasonable.
But could think of a test case that want core to execute `exit;` ?